### PR TITLE
Latesteq 327

### PR DESCRIPTION
**Pull request by ehunter-usgs**
Add EventsNearbyView that is used to select events to associate.

### CODE REVIEW

**Comment by emartinez-usgs** [comment]
EventsNearbyView
- DEFAULTS.url is never used.
- Search URL stub should be configurable via installation
- Should handle ajax errors
- Associate product is never created nor sent.

Question: Could this be made more view-like? I.E. extend EventComparisonView, have a model (Collection) to which you are bound. Render method...

Question: Is AssociateEventView needed? Maybe use generic SendProductView; optionally with custom formatProduct method.

Question: Should we use green/red buttons? I like green because it is an active action being taken by the user. Cancel is more of a passive action to do nothing. I would reserve red buttons for delete-like actions.

**Comment by jmfee-usgs** [comment]
Use $CONFIG['OFFSITE_HOST'] when building the fdsn search url, it can be added to EventConfig in event.php.

**Comment by jmfee-usgs** [comment]
AssociateEventView is still needed, or something similar, to generate the correct associate product(s) in case non-preferred information is preventing association.

**Comment by ehunter-usgs** [comment]
I am not sending an associate product because I thought that would be handled during the implementation of the AssociateProductView.  This ticket just creates a skeleton for that view.

**Pull request merged**
